# Generated by Django 4.1.1 on 2022-10-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('adress', models.TextField()),
                ('entrance', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('flat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('unique_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('created_from_id', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('incident', models.BooleanField(default=False)),
                ('edited_by', models.CharField(max_length=255)),
                ('edited_organization', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('has_question', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=255)),
                ('deny_id', models.IntegerField()),
                ('closed_at', models.DateTimeField()),
                ('time_from', models.TimeField(default=None)),
                ('time_until', models.TimeField(default=None)),
                ('adress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Managing',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('inn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Performing',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('inn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('return_count', models.IntegerField()),
                ('last_return_at', models.DateTimeField()),
                ('at_revision', models.BooleanField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('performing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.performing')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('evaluation', models.IntegerField()),
                ('free', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('cardpay', models.BooleanField(default=False)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='defect_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.defect'),
        ),
        migrations.AddField(
            model_name='adress',
            name='managing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.managing'),
        ),
    ]
