# Generated by Django 4.1.1 on 2022-10-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='revision',
            field=models.IntegerField(default=None),
        ),
    ]
