# Generated by Django 4.1.1 on 2022-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_defect_nickname_alter_defect_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='time_from',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_until',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
