# Generated by Django 4.1.1 on 2022-10-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='time_from',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_until',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
