# Generated by Django 4.1.1 on 2022-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performing',
            name='inn',
            field=models.CharField(max_length=30),
        ),
    ]
