# Generated by Django 4.1.1 on 2022-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_performing_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managing',
            name='inn',
            field=models.CharField(max_length=30),
        ),
    ]
