# Generated by Django 4.1.1 on 2022-10-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_managing_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='floor',
            field=models.CharField(max_length=255),
        ),
    ]
