# Generated by Django 4.1.1 on 2022-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_adress_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='flat',
            field=models.CharField(max_length=255),
        ),
    ]
