# Generated by Django 4.1.1 on 2022-11-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_adress_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='adress',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
