# Generated by Django 4.1.1 on 2022-11-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_adress_latitude_adress_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='entrance',
            field=models.CharField(max_length=255),
        ),
    ]
